{% set python_min = "3.12" %}
{% set version = "2026.1.2" %}

package:
  name: polsarpro
  version: {{ version }}

source:
  url: https://github.com/satim-co/PolSARpro/archive/{{ version }}.tar.gz
  sha256: 29df1477208090fd83b192a8affd2bb42d167f27ca86193eb1910433ba12109b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - gdal
    - rasterio
    - geopandas
    - pandas
    - xarray
    - netcdf4
    - rioxarray
    - dask
    - bottleneck
    - jupyter
    - zarr
    - pyyaml

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - polsarpro
  commands:
    - pip check

about:
  home: https://github.com/satim-co/PolSARpro
  summary: 'Re-implementation of selected PolSARpro functions in Python, following the scientific recommendations of PolInSAR 2021.'
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://polsarpro.readthedocs.io

extra:
  recipe-maintainers:
    - odhondt
